# Generated by Django 4.1.2 on 2022-10-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unlike',
            old_name='like',
            new_name='unlike',
        ),
    ]
